#!/usr/bin/env php
<?php 
use ClanCats\Station\PHPServer\Server; 
use ClanCats\Station\PHPServer\Request;
use ClanCats\Station\PHPServer\Response;

array_shift( $argv );

if ( empty( $argv ) )
{
	$port = 80;
} else {
	$port = array_shift( $argv );
}

require 'vendor/autoload.php';

$server = new Server( '127.0.0.1', $port );

// start listening
$server->listen( function( Request $request ) 
{
	$html = "<h1>PHP Raw Socket Server Demo</h1>";
	$html .= "<p><strong>Method:</strong> " . htmlspecialchars($request->getMethod()) . "</p>";
	$html .= "<p><strong>URI:</strong> " . htmlspecialchars($request->getUri()) . "</p>";
	$html .= "<h3>Headers:</h3><ul>";
	foreach ($request->getHeaders() as $key => $val) {
		$html .= "<li><strong>" . htmlspecialchars($key) . ":</strong> " . htmlspecialchars($val) . "</li>";
	}
	$html .= "</ul>";

	return new Response($html);
});